"""initial users and trips

Revision ID: aca1bd348b9d
Revises: 
Create Date: 2026-04-04 22:15:38.143658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca1bd348b9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('college_name', sa.String(length=512), nullable=True),
    sa.Column('college_place_id', sa.String(length=256), nullable=True),
    sa.Column('college_lat', sa.Float(), nullable=True),
    sa.Column('college_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_user_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('destination_place_id', sa.String(length=256), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('destination_label', sa.String(length=512), nullable=False),
    sa.Column('time_bucket', sa.String(length=64), nullable=False),
    sa.Column('vacant_seats', sa.Integer(), nullable=False),
    sa.Column('seats_needed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination_place_id'), 'trips', ['destination_place_id'], unique=False)
    op.create_index('ix_trips_destination_time', 'trips', ['destination_place_id', 'time_bucket'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index('ix_trips_destination_time', table_name='trips')
    op.drop_index(op.f('ix_trips_destination_place_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('users')
    # ### end Alembic commands ###
